api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
        multipart: [ 'multipart/form-data' ]
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    use_symfony_listeners: true
